services:
  db:
    image: postgres:15
    container_name: quiz_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: quiz_redis
    volumes:
      - redis_data:/data

  web:
    build: ./backend
    container_name: quiz_web
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  test:
    profiles: ["test"]
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings_test
      - PYTHONUNBUFFERED=1
    entrypoint: ""
    command: python manage.py test -v 2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build: ./frontend
    depends_on:
      - web
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
  redis_data:
