version: '3.9'

services:
  db:
    image: postgres:15
    container_name: quiz_db_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_test  # osobna baza dla testów
    ports:
      - "5433:5432"  # inny port niż prod
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: quiz_redis_test
    ports:
      - "6380:6379"
    volumes:
      - redis_data_test:/data

  web:
    build: ./quiz_app 
    container_name: quiz_web_test

    volumes:
      - ./quiz_app:/app
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres_test
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=core.settings_test
      - PYTHONUNBUFFERED=1
    command: pytest
    entrypoint: ""
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data_test:
  redis_data_test: