# Generated by Django 5.0.6 on 2026-08-02 01:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('score', models.IntegerField(null=True)),
                ('quiz_time', models.DateField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_histories_quiz', to='quizzes.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_histories_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_quizhistory',
            },
        ),
    ]
